apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jukebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jukebox
  template:
    metadata:
      labels:
        app: jukebox
    spec:
      volumes:
        - name: wmountpath
          persistentVolumeClaim:
            claimName: log
      containers:
        - name: app
          image: emilpradeep/jukebox:v4
          ports:
            - containerPort: 8080
          env:
            - name: logging.config
              value: classpath:logback.xml
            - name: logging.file
              value: /Users/emil/Documents/wisilica/logs/jukebox.log
          volumeMounts:
            - name: wmountpath
              mountPath: /Users
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: jukebox
spec:
  selector:
    app: jukebox
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
